### ISSUE TITLE
Support default index.html with multiple --dir folders

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#100]
Right now if you have a bunch of static paths with `--dir`, only the first one is checked for a default `index.html`. Instead it might be better to check all static paths for an `index.html`, and only fall back to `simple-html-index` if that fails.

Failing test here:
https://github.com/mattdesl/budo/blob/master/test/test-static-folders.js

**Comment by bcomnes** [comment]
I think I ran into this the other day, but I wasn't sure what was going on.  (Budo rocks btw!)

**Comment by yaycmyk** [comment]
:+1: I had to make some changes to my project structure due to this. Would be nice to not need to...

**Comment by mattdesl** [comment]
Should be fixed in `6.1.0`. Let me know if you hit any issues.
