### ISSUE TITLE
Issue with absolute path as entry in Windows

### ISSUE THREAD

**Issue by edankwan** [mattdesl/budo#103]
It looks that there is some conflict with the Windows drive label colon symbol in the `map-entry.js`.

If I pass C:/foobar as entry like `budo('C:/foobar.js', {...})`, it will mistreat `C` as the module and it will show the error Cannot find module C

**Comment by mattdesl** [comment]
Thanks - I am guessing `browserify C:/foobar.js` works as intended?

**Comment by edankwan** [comment]
Yes, it works fine with browserify

**Comment by edankwan** [comment]
I am pretty sure it is because of this: https://github.com/mattdesl/budo/blob/master/lib/map-entry.js#L11

Not sure if you do that for some features of budo(I am still new to it). I know that I can just use relative path but I discovered this issue with your codevember watch script that use `path.resolve()` and returning an absolute path and causing the error.

**Comment by mattdesl** [comment]
Ah yeah, that is an issue. The following is a feature to "remap" the URL that the index.html will point to. 

`budo src/index.js:bundle.js`

Maybe the split regex should just ignore drives as a special case.

**Comment by mattdesl** [comment]
@edankwan Can you test `6.0.3` and let me know if that fixes it?

**Comment by edankwan** [comment]
Not yet, it was my bad, after `path.resolve()` the the path will become `C:\foobar` not `C:/foobar`

**Comment by mattdesl** [comment]
Ok, try `6.0.4`. :laughing: 

Updated the test case as well:
https://github.com/mattdesl/budo/blob/953afac2b7c0d4bb254fec3a31cad907eb508ded/test/test-map-entry.js#L15

**Comment by mattdesl** [comment]
This is all good @edankwan ?

**Comment by edankwan** [comment]
Oh, sorry for the belated reply. Yes, it is all good :)
