### ISSUE TITLE
New Logs

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#105]
The next version of `garnish` is going to make budo logs look like this:

<img width="591" alt="screen shot 2015-11-16 at 9 55 47 am" src="https://cloud.githubusercontent.com/assets/1383811/11184996/84712cd6-8c48-11e5-9bf1-0e25de8da4a7.png">

If you have suggestions/etc before this change comes through, post them here or in [garnish#20](https://github.com/mattdesl/garnish/issues/20).

**Comment by superguigui** [comment]
It's looking good :) 

Did you check with dark background ?

Also I was thinking, successful GET requests aren't always relevant when developing, I'm usually more interested in Browserify cycles or failed requests. What about a mode between `--no-stream` and normal mode ? :)

If anyone else is interested I'll make an issue / PR.

**Comment by mattdesl** [comment]
Here is the "Pro" theme for OSX:

<img width="593" alt="screen shot 2015-11-16 at 10 30 45 am" src="https://cloud.githubusercontent.com/assets/1383811/11185914/1c0b8d6c-8c4d-11e5-89df-780a1af69445.png">

I could add a compact/minimal-http mode which only logs browserify + 400 level requests. I'm also adding a `verbose` flag which can print some additional debug messages. Any other information that might be good to log?

**Comment by superguigui** [comment]
:+1: 

Seems already quite verbose to me, I wouldn't know what else to log... Browserify errors ?

**Comment by yoshuawuyts** [comment]
@superguigui Browserify errors should be logged already (':

**Comment by mattdesl** [comment]
This is in 7.0 now, I did a major bump since a lot of ndjson flags have changed.
