### ISSUE TITLE
Clarify if budo's browserify uses the browserify field in package.json

### ISSUE THREAD

**Issue by bcomnes** [mattdesl/budo#106]
Does Budo's browserify honor the package.json found in the project folder?  (It doesn't look like it does, right?)  Maybe this should be clarified in the docs?

**Comment by mattdesl** [comment]
Yup, since it just launches watchify/browserify, it will honour the `"browserify"` field. 

I can add a note about this tomorrow. The feature is not great practice, though, unless you are in on a project directory (i.e. not a module).

**Comment by mattdesl** [comment]
Added to docs.
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#browserify-arguments

**Comment by bcomnes** [comment]
:+1:

**Comment by letmaik** [comment]
I tried this but it doesn't seem to work.

**Comment by yoshuawuyts** [comment]
it should; it might have something to do with the entry dir from where it's
being resolved. I believe there's a flag to set it (:
