### ISSUE TITLE
Can't change serving root

### ISSUE THREAD

**Issue by yaycmyk** [mattdesl/budo#108]
I'm not sure if I'm doing something wrong here, but I'd like to use the `site/` directory as the server base.

Here's my full command:
```
budo site/index.js:site/dist/bundle.js -d ./site -H localhost --colors --live --open --pushstate --iw -- -t babelify -t brfs
```

Am I misunderstanding how `-d` works, and is there a different flag that will do what I'm trying to accomplish?

**Comment by yoshuawuyts** [comment]
Have you tried doing the minimal setup, e.g. omitting all other flags but `-d`? It seems you're on the right track though.

**Comment by yaycmyk** [comment]
Alright I figured it out. After applying `-d site`, the base changes, so the part after the colon has to be adjusted to assume that is where it is being outputted.

So it becomes:
```
budo site/index.js:dist/bundle.js -d ./site -H localhost --colors --live --open --pushstate --iw -- -t babelify -t brfs
```

**Comment by yoshuawuyts** [comment]
Glad you figured it out (': :sparkles:

**Comment by mattdesl** [comment]
Cool. :smile: If you feel the docs could be improved I will accept PRs!
