### ISSUE TITLE
Explore browser-sync

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#11]
Might be nice to explore different options for live reload

**Comment by joeybaker** [comment]
FWIW, I played a bit with doing this this weekend. It's definitely better than tiny-lr (css injection works much smoother, and the logging options are better). It _shouldn't_ be hard to implement. Would you be interested in a PR?

(btw… thanks for budo. I've used it to basically replace https://github.com/Techwraith/ribcage-preview/ and life is much better – cheers!)

**Comment by mattdesl** [comment]
Sounds cool! 

I wonder what kind of implications it has switching to a different LR framework? Is it something we would want the user to be able to choose between? 

Also from what I can tell with browser-sync is that it really tries to be "the whole package" and also does things like serving localhost + internal IP (with a proxy). Is there a way to utilize it just for live-reload? 

I haven't really run into any major roadblocks with tiny-lr so far (mainly why I haven't bothered to explore alternatives). But I also haven't been doing much CSS work lately.

**Comment by joeybaker** [comment]
Yea, BS is way more than tiny LR. But, I found it works well when proxying the dev (budo) server. This allows BS to automatically do things like script injection, show the user a notification on file change, and keep multiple devices in sync, (and the CSS injection is much better). I got this working with livereact-reload too.

**Comment by joeybaker** [comment]
@mattdesl I've got a little bit of time, and thought about working on this – but I saw https://twitter.com/mattdesl/status/640204677787709440 – is BrowserSync integration still something you're interested in?

**Comment by yoshuawuyts** [comment]
@joeybaker oh wow, it looks like browsersync has quite the feature set but looks yuck to set up. I can see the added value though.

**Comment by mattdesl** [comment]
@joeybaker Do you have a fork I can look at? It seems like a pretty huge dependency to add to budo. :confused: Maybe there is a cleaner way we can integrate the features of budo (like [watchify-middleware](https://github.com/mattdesl/watchify-middleware/blob/master/index.js)) with those in BrowserSync.

Regarding `--live-plugin` - that was a specific feature of LiveReload Chrome plugin that I removed from CLI (still available via `budo.live({ plugin: true })`). The regular LiveReload `<script>` injection and CSS reloading should continue to work in budo@5.

**Comment by joeybaker** [comment]
Yea, it's a really big dependency :\

I haven't started an integration, but here's what I've done to get them to play nicely with each other: https://gist.github.com/9b06bc47dc685e3cb007

**Comment by yoshuawuyts** [comment]
That looks rough, not sure it's worth pulling in.

**Comment by joeybaker** [comment]
Here's a smaller version of what's necessary: https://gist.github.com/joeybaker/9b06bc47dc685e3cb007

**Comment by yoshuawuyts** [comment]
That looks a lot better! Still unsure if it belongs in budo or should be used as an external plugin. Maybe having an example in the repo would be a good middleground? Ghmm.

**Comment by mattdesl** [comment]
I'm going to close this since it has not got much traction. I think it's best to stick with `tiny-lr` for the time being. :smile: Budo can always be integrated with your favourite live-reload solution like BrowserSync or browserify-hmr.
