### ISSUE TITLE
Works great with browserify-hmr!

### ISSUE THREAD

**Issue by Widdershin** [mattdesl/budo#112]
Just thought I would let you know that budo works great when paired with [browserify-hmr](https://github.com/AgentME/browserify-hmr). I've been using it for all my hot reloading needs.

Here's an example of how I'm using it:
https://github.com/Widdershin/cycle-hot-reloading-example

Note, this isn't an issue you need to worry about, just wanted to thank you for making such a cool (and compatible) piece of software. Feel free to close this issue :smile:

**Comment by mattdesl** [comment]
Yeah! It also works well on the command line. I've been meaning to plug `browserify-hmr` somewhere in the docs. :smile:

**Comment by yoshuawuyts** [comment]
Ooh, I did not know this. Rad!

**Comment by mattdesl** [comment]
Added to docs. Budo also works with vueify's HMR and livereactload.
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#hot-module-replacement

**Comment by sombriks** [comment]
> budo src/main.js:build.js --live -o -- -p browserify-hmr

This is amazing. This single line replaces watchify and http-server from standard template from vue-cli and makes my setup cleaner.

Budo lives on my "npm run dev" now.
