### ISSUE TITLE
Push state with multiple / will break

### ISSUE THREAD

**Issue by mikkoh** [mattdesl/budo#113]
Let's say you have a url like `http://0.0.0.0/grid/10` an error will be thrown in the console:

`Uncaught SyntaxError: Unexpected token <`

**Comment by mattdesl** [comment]
I just tested a bit, seems like it's because the browser is requesting the `bundle.js` and `main.css` with a different base path. Other servers have the same issue, like [pushstate-server](https://github.com/scottcorgan/pushstate-server).

Looks like the recommended fix is to add a `<base>` tag:

```html
<head> 
  <base href="/">
  <!-- scripts, stylesheets, etc -->
</head>
```

**Comment by mattdesl** [comment]
Hmm maybe this should be included in default index if `--pushstate` is set?

Reopening.

**Comment by mattdesl** [comment]
I'm going to close this and just direct users to docs instead of magically changing the HTML when `--pushstate` is added.
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#pushstate
