### ISSUE TITLE
File size in log is way different than what is in the browser

### ISSUE THREAD

**Issue by yaycmyk** [mattdesl/budo#115]
I can't really share my environment (private source), but I'm seeing something interesting... The file size in the logger is generally at least 2x what the actual bundle size is when received by the browser.

![screen shot 2015-12-10 at 5 30 42 pm](https://cloud.githubusercontent.com/assets/570070/11730552/d69371d0-9f63-11e5-9e40-bd5cd45e1df0.png)

<img width="598" alt="screen shot 2015-12-10 at 5 30 56 pm" src="https://cloud.githubusercontent.com/assets/570070/11730554/d9050302-9f63-11e5-9865-f6d54d42d7a3.png">

The script to start budo is:
```bash
budo site/index.js:dist/bundle.js -d site -H localhost --colors --live --open --pushstate --iw -- -t babelify -t brfs
```

**Comment by mattdesl** [comment]
Thanks for the bug report. I will take a look this week! :smile:

**Comment by yoshuawuyts** [comment]
@mattdesl not sure what you're currently using, but if it isn't working well this should be fail-proof:
- https://github.com/TabDigital/node-middleware-log

It's a bit dirty, but should work reliably. If that's not a good fit, perhaps [size-stream](https://www.npmjs.com/package/size-stream) will work.

Hope this is helpful (':

**Comment by caspervonb** [comment]
Looks like the log is logging the raw size, and its transferred with gzip compression?

**Comment by yaycmyk** [comment]
I don't think so. The browser log says it is not.

**Comment by mattdesl** [comment]
The current solution in `server.js` is basically the same as the [content-length](https://github.com/scottcorgan/content-length/blob/master/index.js) module. Maybe `size-stream` will be a better fit, though.

**Comment by yaycmyk** [comment]
:tada: Thanks @mattdesl!

**Comment by mattdesl** [comment]
This should be mostly fixed, let me know if you see further issues.

When the server code is refactored to use `filed` and other stream-based stuff (see #80), I will try to use `size-stream` or a similar module.
