### ISSUE TITLE
livereactload demo

### ISSUE THREAD

**Issue by anvaka** [mattdesl/budo#123]
I saw it was mentioned [here](https://github.com/mattdesl/budo/issues/20), but I was wondering if there is a way to use budo with react hot reload?

**Comment by mattdesl** [comment]
Yep, it should work just the same except instead of using `watchify`, you use `budo` and pass the `--plugin` option after a full stop.

I added a short section here:
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#hot-module-replacement
