### ISSUE TITLE
Allow dynamic generation of index.html

### ISSUE THREAD

**Issue by ashaffer** [mattdesl/budo#127]
For server-side rendering apps, it'd be nice to be able to specify your index generator as a function parameterized by the current request.

**Comment by mattdesl** [comment]
Can you provide a bit more details/code examples of how this might look?

Currently there are two fields that can be used to modify the response of the default index:

- `defaultIndex` a function which returns a stream that writes the default HTML contents
- `middleware` a function with `(req, res, next)` parameters that can override default behaviours

**Comment by ashaffer** [comment]
Hmm maybe the `middleware` option can do what i'm thinking. But essentially I just want `defaultIndex` to receive the request, so that it can say, serve a different index file based on the current url, or cookies or whatever.

**Comment by yoshuawuyts** [comment]
@ashaffer what you're describing feels relatively complex; I don't think this falls within the scope of what `budo` does. Instead I feel you should be able to roll your own, using the components that `budo` is built on, as described in #122. That way `budo` stays lean, but you can adjust whatever you need to fit your use case. Does that work for you?

**Comment by ashaffer** [comment]
@yoshuawuyts Is it complex? Rendering a dynamic index.html seems as simple as could be. Just expose a function like: `index(req) -> Promise`. Problem solved, somewhere inside budo this is already happening anyway i'm sure.

**Comment by mattdesl** [comment]
> I just want defaultIndex to receive the request, so that it can say, serve a different index file based on the current url, or cookies or whatever.

Hmm, it isn't so simple right now. The server checks if a default index exists in any of the static paths, and if not, *then* it calls `defaultIndex` to respond with the HTML stream. 

Perhaps we could add a `findDefaultIndex` function option... but it's getting a bit hairy/complex. I think what you are aiming for *should* be possible with `middleware`, however, you might need to add [inject-lr-script](https://www.npmjs.com/package/inject-lr-script) yourself. Maybe some changes in budo could be made to improve this (like querying the current live options) – I have run into this problem myself in another project.

**Comment by mattdesl** [comment]
Another option:

Right now I'm exploring/testing a `forceDefaultIndex` flag (may rename it). It will always serve the `defualtIndex` stream instead of something local. We could add a second parameter to the function, so things look like this:

```js
budo({
  forceDefaultIndex: true,
  defaultIndex: function (opt, req) {
      if (req.url === '/index.html') return simpleHtmlStream();
      else return someOtherHtmlStream();
  }
})
```

**Comment by ashaffer** [comment]
Ya that looks great to me.

**Comment by mattdesl** [comment]
> serve a different index file based on the current url, or cookies or whatever.

Ignore my last post. This isn't actually possible since the `defaultIndex` stream is only used when the `req.url` matches `/index.html` or `/`.

I think for custom routing you should use a `middleware` function; the only downside is you will not get LiveReload injected into an HTML response.

P.S. The server code has just been refactored a bunch. It should be a bit easier to grasp and also add custom middlewares.

**Comment by mattdesl** [comment]
I don't think this issue is relevant with 10 anymore, all the features should be there for custom middlewares/index/etc. Thanks!
