### ISSUE TITLE
not working with `proxychains4`

### ISSUE THREAD

**Issue by account-archived-0** [mattdesl/budo#129]
I'm on an OSX, currently using proxychains4 with zsh (i.e. in my `.bash_profile`, I have `proxychains4 -q zsh`):

I wasn't quite able to get budo works - it would just get stuck and not to start the server

<img width="639" alt="screen shot 2016-01-22 at 3 23 15 pm" src="https://cloud.githubusercontent.com/assets/10269911/12504812/30949220-c11c-11e5-9d81-f7887cf59216.png">

Later on I realized if I stop using proxychains4, budo would work nicely.

Turns out budo is not compatible with proxychains4.

**Comment by mattdesl** [comment]
Going to close this since it's a bit stale.
