### ISSUE TITLE
Quickly output static version for sharing prototypes?

### ISSUE THREAD

**Issue by andyinabox** [mattdesl/budo#138]
Ok, I'm really enjoying working with budo, but here's a common scenario I am encountering:

1. Get jammin' in no time with budo.
2. After some playing around I land on something interesting that I want to share.
3. STOP and hack together a build process which inevitably feels way too cumbersome after jammin' with budo.

I'm thinking it would be great to be able to have a way to share a budo project quickly by spitting out a static site, which can then published using [`gh-pages`](https://www.npmjs.com/package/gh-pages) or any other publishing tool. I sketched something out below, but I'm wondering if there's a better way to do this that would fit in with your development?

https://github.com/andyinabox/budo-demo/

The goal is to make it really quick and easy, and avoid having to use grunt/gulp etc. but just run it through the "scripts" option in my project's "package.json" file.

**Comment by yoshuawuyts** [comment]
I think this is related to https://github.com/mattdesl/budo/issues/60

**Comment by andyinabox** [comment]
Ah yes, @yoshuawuyts is correct, #60 pretty much covers what I'm talking about here
