### ISSUE TITLE
Improved HTTPS Support

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#142]
Bassic SSL has been added, but maybe some features could be added:

- Auto-generate self-signed keys with [pem](https://www.npmjs.com/package/pem)
- Should we also run an HTTP server at the same time?
- Make sure `--open` provides a nice UX

**Comment by yoshuawuyts** [comment]
Keen to hear what you have in mind for "Make sure --open provides a nice UX"

**Comment by mattdesl** [comment]
> Keen to hear what you have in mind for "Make sure --open provides a nice UX"

Basically this just means, if we use `pem` to generate a cert then `--open` should *probably* open a URL that works with that cert, otherwise it's kind of useless.

**Comment by yoshuawuyts** [comment]
ah, yeah that makes sense hah

**Comment by mattdesl** [comment]
budo@9 will generate a self-signed certificate if no `--cert` / `--key` flag is passed. This is a breaking change from previous versions but much more convenient.

LiveReload has been fixed and the `--open` flag works nicely now. Added some more docs on how to get HTTPS/SSL working. Overall pretty easy to work with now! 🎉
