### ISSUE TITLE
LiveReload Errors when ssl = true

### ISSUE THREAD

**Issue by gdenisov** [mattdesl/budo#147]
In console I get:

GET https://192.168.1.237:35729/livereload.js?snipver=1 net::ERR_CONNECTION_CLOSED

 Works perfectly fine when ssl = false.

**Comment by mattdesl** [comment]
This should be fixed now in budo@9. Make sure the URL you load is the same IP that is listed in the terminal on server start.

Also just a heads up — budo@9 will generate a self-signed certificate if no `--cert` / `--key` flag is passed. This is a breaking change from previous versions.
