### ISSUE TITLE
browserify "browser" field issue

### ISSUE THREAD

**Issue by dfcreative** [mattdesl/budo#148]
Hi @mattdesl!

I have simple setup for [nogl-shader-output](https://github.com/dfcreative/nogl-shader-output) - I want to set mapping to gl-shader-output

``` json
"browser": { "./index.js": "gl-shader-output" }
```

for that module.

Doing `browserify` command works alright - it bundles gl-shader-output, but running budo gives

``` sh
Error: ENOENT: no such file or directory, lstat 'C:\Users\dmitry\Dropbox\Projects\nogl-shader-output\gl-shader-output'
```

It tries to look up for a file, not a package.
I tried updating budo’s browserify dep to @13.0.0, but it didn't work.

Related https://github.com/substack/node-browserify/issues/1539

**Comment by mattdesl** [comment]
Is this still an issue in `budo@10.x`?

**Comment by dfcreative** [comment]
@mattdesl yes. It still tries to resolve package name as path first. Although browserify now does the same, so the issue can be closed for now I guess.
