### ISSUE TITLE
Pushstate routes with a decimal are treated as file names

### ISSUE THREAD

**Issue by BrendanNeufeld** [mattdesl/budo#150]
I am trying to use coordinates as a route. `pushstate=true` works for all other routes except these coordinate routes. It appears that the server thinks these are file names. I am not sure how budo would distinguish between 'actual' files and routes though. There might need to be a setting or some kind of condition,  similar to mod_rewrite.

**Comment by yoshuawuyts** [comment]
Do you have some example code? I don't quite follow what you're doing. Thanks!

**Comment by mattdesl** [comment]
Example case: `localhost:8080/30.520,50.235` (e.g. lat/long)

So the way that [connect-pushstate](https://www.npmjs.com/package/connect-pushstate) works is that it looks for a file extension, and it's under the impression that `253.501` has one. 

I think we could somehow expose an options object to the user to handle regexes for allowing/ignoring pathnames in the push state middleware. Or, you could add your own custom `middleware` function and set the `pushstate` option to false.

Going to explore a bit more.

**Comment by cheapsteak** [comment]
how do you add your own middleware?

this might be solved by using the connect-modrewrite middleware

this is working for me with browserSync:

```
middleware: [
  modRewrite([
    '^[^\\.]*$ /index.html [L]'
  ])
]
```

**Comment by mattdesl** [comment]
Budo has a `middleware` option which can accept an array of functions, and they can do the same thing as `connect-pushstate`, `connect-modrewirte`, etc.

**Comment by BrendanNeufeld** [comment]
Great, the `connect-modrewrite` middleware worked perfectly.

**Comment by yaycmyk** [comment]
@BrendanNeufeld What did your end code look like? I tried what @cheapsteak posted and it doesn't work for me.

**Comment by mattdesl** [comment]
@yaycmyk You can do something like this without any additional modules, and also tweak the regex to your application.

```js
var url = require('url');
var path = require('path');

var pushstate = function (req, res, next) {
  var rootUrl = '/';
  var pathname = url.parse(req.url).pathname;
  var hasExtension = Boolean(path.extname(pathname));
  if (!hasExtension || /.*[0-9\.]+\,[0-9\.]+$/.test(pathname)) {
    req.url = rootUrl;
  }
  next();
};

require('budo').cli(process.argv.slice(2), {
  middleware: pushstate
});
```

**Comment by BrendanNeufeld** [comment]
@yaycmyk  Unfortunately had to specify the section routes (quick fix), but you could adjust the rewrite rules to something more generic.
```
var modRewrite = require('connect-modrewrite');
var b = budo(config.entry, {
  serve: config.bundle,
  open: true,
  dir: config.output,
  stream: process.stdout,
  // pushstate: true,
  middleware: [
    modRewrite([
      // '\/pano\/40\.7594089,-73\.9851303 index.html [L]'
      '(\/pano\/|\/news\/)(.*) index.html [L]'
    ])
  ]
}); 
```

**Comment by yaycmyk** [comment]
I also ended up using `connect-modrewrite` to solve this, but it would be great to have it be natively supported @mattdesl if possible. Maybe require a trailing slash to make it easier to differentiate?

**Comment by mantoni** [comment]
The underlying issue with this is with the way [connect-pushstate handles filenames](https://github.com/brentertz/connect-pushstate/issues/1). I've [suggested a fix](https://github.com/brentertz/connect-pushstate/pull/2) and @brentertz is also [working on a new option](https://github.com/brentertz/connect-pushstate/tree/disallow) to help address this. In my case, both of the above linked solutions work with budo if I pass options to `connect-pushstate` and set `allow` to `\\.[a-z]+$` or `disallow` to `[\\.0-9]+$`.

However, both solutions require options to be passed down to `connect-pushstate`. Now my question is, would @mattdesl accept a pull request with a new option called `--pushstate-disallow exp` which activates `--pushstate` and passes the given expression as the `disallow` option to `connect-pushstate`? The same could be done with `--pushstate-allow exp` for the `allow` option.

**Comment by mantoni** [comment]
An new `connect-pushstate` release was made two weeks ago and I've made a pull request that makes this work for me. @BrendanNeufeld @yaycmyk Can you check if my suggestion works for you?

**Comment by mattdesl** [comment]
Ok.... finally I got around to merging everything in with 10. Now `--pushstate` can be specified in budo with subarg. See here:
https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#pushstate

Thanks for all the work on this, sorry it took so long. :beers:

**Comment by mantoni** [comment]
Awesome 🎉  Thank you!
