### ISSUE TITLE
flag --serve short version does not work

### ISSUE THREAD

**Issue by fibo** [mattdesl/budo#151]
Hi,

thank you for budo, it is my preferred choice to use as a dev server.

I noticed that using `-s` short version of `--server` flag option does not work.

To reproduce error:

1. Clone [fibo/redux-examples](https://github.com/fibo/redux-examples/tree/v0.2.0) tag **v0.2.0**
2. Change [this line](https://github.com/fibo/redux-examples/blob/v0.2.0/package.json#L9) to `"example_counter": "budo -s static/bundle.js -d counter counter/index.js -- -t babelify"`, i.e. replacing `--serve` with `-s`.
3. Run `npm run example_counter`.

I get a 404 for */static/bundle.js*

<img width="773" alt="screen shot 2016-04-26 at 10 33 51" src="https://cloud.githubusercontent.com/assets/176730/14811842/75762ca0-0b9a-11e6-9da0-a3c508bb94e1.png">

I expected that using the shorter version worked, is there maybe some positional order for options?

**Comment by mattdesl** [comment]
Nice catch! Should be fixed in `8.2.2`. Thanks. 😄
