### ISSUE TITLE
--pushstate not working for /foo/bar

### ISSUE THREAD

**Issue by mantoni** [mattdesl/budo#159]
Hi, thanks for budo. I like it 🍺

The thing I stumbled upon is that `--pushstate` does not serve up the `/index.js` file when calling `/foo/bar`, instead it wants to serve `/foo/index.js`.

I’m invoking budo like this:

```
budo . --pushstate --live -- -t sheetify/transform -t es2040
```

I can fix it by [changing this line](https://github.com/mattdesl/budo/blob/master/lib/middleware.js#L122) to `entry: '/' + entrySrc`, but that doesn’t seem to be the right thing to do.

I already tried adding `--serve /index.js`, but then the browserify transforms stopped working.

Thanks for your help!

**Comment by mattdesl** [comment]
You should add a `<base>` tag when dealing with pushstate:

https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#pushstate

**Comment by mantoni** [comment]
That makes sense, but I can’t do that with the automatically generated web page, or can I?
