### ISSUE TITLE
Idea: integrate auto-install

### ISSUE THREAD

**Issue by maximilianschmitt** [mattdesl/budo#165]
Hi, just wanted to suggest checking out [`auto-install`](https://www.npmjs.com/package/auto-install) to see if it could be integrated into budo.

Could be cool! :)

**Comment by mattdesl** [comment]
You can use [installify](https://github.com/hughsk/installify) for this, like so:

```sh
budo index.js:bundle.js --live -- -t [ installify --save ]
```

:smile:
