### ISSUE TITLE
Absolute path resolution

### ISSUE THREAD

**Issue by josephluck** [mattdesl/budo#168]
I'm not sure if I've missed this in the docs (I've read them all and looked through all the issues to see if this has been asked before) so please excuse me if I have missed something.

I'm looking for a way to import modules in my project resolving from the base directory instead of having to specify the path relative to the current file. For example, where I'm writing:

`import TodosList from '../../elements/todos-list'`

I'd actually like to write:

`import TodosList from 'elements/todos-list'`

I've tried out the --dir option: `--dir=.` but it didn't seem to work.

Any suggestions?

**Comment by yoshuawuyts** [comment]
I think a lot of us have gone down that path, and I strongly urge you not to do that as there is no good solution - instead consider using less nesting; it's the least magicky solution / most node-y way of getting paths to work alright. Hope this was useful, cheers!

**Comment by josephluck** [comment]
Thanks @yoshuawuyts. 

And thanks for Choo!

**Comment by matthewmueller** [comment]
just saw this one. for what it's worth, browserify supports the `NODE_PATH` env variable, so if you did: `NODE_PATH=elements budo index.js`, you could import `import TodoList from todo-list`

I've used this in a bunch of apps previously, upside is that it's cleaner, downside is that it's not immediately clear where things are (whether they're remote or local) especially for new teammates. it also probably slows down the build a bit.

**Comment by mattdesl** [comment]
I think I'll close this since it's not an issue with budo itself. :smile: I agree with @yoshuawuyts.
