### ISSUE TITLE
Bundle references broken on second+ level routes w/pushstate

### ISSUE THREAD

**Issue by timwis** [mattdesl/budo#178]
If you serve an app using `--pushstate` and your app has a router that allows 2+ level routes, ie (`/posts/42` instead of just `/posts`), the `<script src="index.js">` reference breaks, as the browser attempts to get `/posts/index.js` and gets a 404.

This happened with bankai too: yoshuawuyts/bankai#32. In that case, we [resolved it](https://github.com/yoshuawuyts/bankai/pull/78) by using an absolute path to the bundle. 

I tried using `--serve '/index.js'` but that pulls in the uncompiled `index.js` rather than just changing the path of the compiled file.

Thoughts?

**Comment by matthewmueller** [comment]
ran into this too, there's a fix here: https://github.com/mattdesl/budo/pull/175

**Comment by mattdesl** [comment]
I added some discussion on that here:
https://github.com/mattdesl/budo/pull/175#issuecomment-260006281

I don't know if it's a trivial matter to solve, and maybe there is a way through the CLI that we can print suggestions or warnings to help navigate users toward a certain approach.

**Comment by timwis** [comment]
Adding `--base /` to my `npm start` script seems good to me.

**Comment by mattdesl** [comment]
Ok — closing for now! :smile:
