### ISSUE TITLE
[Windows] Weird output scheme ?

### ISSUE THREAD

**Issue by Pymous** [mattdesl/budo#179]
Heyyyy !

I'm discovering budo, and it look awesome, everything works fine, but I have a small 'issue' with my output it seems.

Instead of looking like the example with Garnish, it's more like ... that : 
![w5diaxv](https://cloud.githubusercontent.com/assets/13593371/19413606/673c9726-9332-11e6-86c0-e76b9ae6efb6.png)

And if I do the same thing and just piping it through garnish : 
![screenshot_1](https://cloud.githubusercontent.com/assets/13593371/19413610/72cec26c-9332-11e6-9d3b-bca7f2d63b01.png)

I'm on Windows 10, using Node v6.6.0, NPM v3.10.3, Budo v9.2.1 and Garnish 5.2.0

Thanks for the work !

**Comment by mattdesl** [comment]
Hmm maybe @yoshuawuyts can chime in here?

**Comment by mattdesl** [comment]
Not sure why `stdout-stream` doesn't work nicely on windows, but for now I'm using a conditional to fall back to `process.stdout`. Maybe we should just evaluate using `process.stdout` on all platforms — I'm not aware of scenarios where it helps?
