### ISSUE TITLE
Cloud9 and LiveReload

### ISSUE THREAD

**Issue by rbrtmrtn** [mattdesl/budo#180]
I'm trying to run Budo on [Cloud9 ](https://c9.io/)(a cloud IDE). The host environment only exposes ports 8080, 8081, and 8082, so I decided to run the web server on 8080 and LR on 8081 with this command:

```
budo scripts/src/index.js:scripts/dist/bundle.js --host $IP --port $PORT --live --live-port=8081
```

where `$IP` is `0.0.0.0` and `$PORT` is `8080`. The server starts up and says 

```
[0001] info  Server running at http://0.0.0.0:8080/ (connect)
[0001] info  LiveReload running on 8081
```

I also added the following snippet to `index.html` to get my LiveReload browser plugin to support a port other than 35729.

```
<script>document.write('<script src="http://myproject.c9users.io:8081/livereload.js?snipver=1"></' + 'script>')</script>
```

So far the web assets are loading fine but LiveReload fails to connect with this error:

```
WebSocket connection to 'ws://0.0.0.0:8081/livereload' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID
```

Is there any way I can force it to use the same host that the snippet was downloaded from?

Thanks!

**Comment by mattdesl** [comment]
Sorry about the massive delay in response — but I've been working on an alternative LiveReload backend that doesn't require a second server. This means the LiveReload script is served on the same host/port as the HTTP requests. It will probably resolve cases like yours.

You can follow progress here:
https://github.com/mattdesl/budo/issues/194

**Comment by mattdesl** [comment]
Should hopefully be all fixed now. Thanks.
