### ISSUE TITLE
If babel throws it seems to kill the server

### ISSUE THREAD

**Issue by matthewmueller** [mattdesl/budo#181]
I'm not 100% sure what's happening but I think if babelify encounters a parsing error, it'll kill the budo process.

**Comment by yoshuawuyts** [comment]
are you using babelify or ... ?

**Comment by mattdesl** [comment]
I haven't been able to reproduce this one yet — any ideas how I can?

**Comment by matthewmueller** [comment]
it's babelify yah, i'm going to close since it's really inconsistent and i'm not even sure it's on budo's end.
