### ISSUE TITLE
Add a directory listing mode?

### ISSUE THREAD

**Issue by brianpeiris** [mattdesl/budo#184]
I often find myself wanting to see a directory listing of the root path, when there isn't an index.html. Could we add a mode for budo to do this? I might be able to start work on it if you're interested.

**Comment by mattdesl** [comment]
This sounds pretty useful — any objections? It seems like other tools (e.g. `http-server`) do this.

**Comment by mattdesl** [comment]
FWIW you can do something like this:

```dev.js```

```js
var serveIndex = require('serve-index')

require('budo').cli(process.argv.slice(2), {
  middleware: serveIndex(__dirname)
})
```

And now use `node dev.js` like you would `budo`, for example:

```sh
node dev.js src/index.js:bundle.js --dir app --live -- -t babelify
```

**Comment by mattdesl** [comment]
Going to close since the above seems to handle this issue without adding a lot of extra complexity to budo core.
