### ISSUE TITLE
kill param for budo

### ISSUE THREAD

**Issue by sombriks** [mattdesl/budo#186]
Hello,

currently i have this in my package.json:

  ```json
"scripts": {
    "dev": "budo src/main.js:build.js -o --live",
    "test": "concurrent 'budo src/main.js:build.js' 'sleep 3 ; mocha --timeout=10000 ; echo \"kill me please\"'"
},
```

i want to change the *echo part* for something like **budo --kill-all**

how such enhancement could take place?

**Comment by mattdesl** [comment]
I think the best approach would be to use the API and call `budo.close()`.

For example:

```js
var app = require('budo').cli(process.argv.slice(2));
if (app) {
  // or you can run your mocha stuff here and close budo on callback
  setTimeout(() => app.close(), 10000);
}
```

**Comment by sombriks** [comment]
Hi @mattdesl !

it's still a work in progress, and you're right, budo API has the solution.

my sample [test case](https://gist.github.com/sombriks/4d8ab3cc481cdb312a24a725e893a6e9) is something like that for the moment:

```
"use strict"

const Nightmare = require("nightmare");
const expect = require("chai").expect;
const budo = require("budo");

describe("\u263C basic tests \u263E", () => {

  const b = budo("../src/main.js");

  it("should check document title", (done) => {
    Nightmare().goto("http://127.0.0.1:9966")
      .wait("#mount").evaluate(() => {
        return document.title;
      }).end().then((result) => {
        expect(result).to.equal("BTT");
        done();
      });
  });

  it("should close test server", (done) => {
    b.close();
    done();
  });
});
```

And this way all tests runs and in the end the test runner itself closes budo.

The answer, in the end, was in the docs all the time, ;-)

**Comment by mattdesl** [comment]
Nice! I could maybe update the main readme with an example of running budo via API. Would that help future users?

**Comment by sombriks** [comment]
@mattdesl you bet it will!

budo alone gives a swift approach do development, and as i figured out (and hope that many others get it too) using this api it can be integrated on testing workflows... maybe much more!

if i haven't said yet, amazing project, budo rocks! please make someday a cool logo so we can buy t-shirts and stickers! :+1:
