### ISSUE TITLE
Crashing memory leak when using budo in firefox 49+

### ISSUE THREAD

**Issue by jaapz** [mattdesl/budo#189]
Since firefox 49+, I've been experiencing a major issue where firefox would completely eat up all available ram when the developer toolkit is open and budo triggers a live reload.

I can reproduce this 100% of the time.

I have no idea how I can debug this, could anyone help me out here?

**Comment by gregtatum** [comment]
I think I may have found it. We're looking into fixing it.

**Comment by gregtatum** [comment]
So it looks like the new debugger interface is leaking the sources on refresh, we're working on a fix for that one. The old debugger interface doesn't appear to be leaking, but it does duplicate the sources in memory like crazy, making it slow and bloated, which is a big problem for projects with large sources and sourcemaps. I found around 10-20 copies of the source maps in memory in the old interface 😮

The new debugger interface is currently in Dev Edition, and my guess is that we'll uplift any fixes for that, but probably not do anything with the old interface.

**Comment by mattdesl** [comment]
Awesome, thanks for the quick reply Greg! :smile:

I've experienced something like this on a WebGL project a while back. Something I noticed is that Firefox likes to hang on to WebGL contexts on refresh — I'm not sure if the latest version still does this or not, or whether it's totally unrelated to the root problem.

**Comment by jaapz** [comment]
@gregtatum that explains why even on 48, my development experience is less then  ideal :) but at least on that version it doesn't crash my computer!

Is moving to firefox dev edition (for now) going to solve it for me?

**Comment by gregtatum** [comment]
https://github.com/devtools-html/debugger.html/pull/1369

There's a fix in place for the memory leak. I'll have to find out when that will land in Firefox. It will for sure be in the next release into Dev Edition (53), although I would guess they'll uplift it to the current Dev Edition (52). Before 51 and below are using the older debugger, and I doubt we'll address the memory issues for that.

**Comment by jaapz** [comment]
@gregtatum awesome, thanks! I'll keep using 48 for now until the fix is released :)

**Comment by mattdesl** [comment]
I guess we can close this? :smile:

**Comment by gregtatum** [comment]
Yup!
