### ISSUE TITLE
Great work : comment

### ISSUE THREAD

**Issue by SilentCicero** [mattdesl/budo#192]
Hey dude, I've been using this for several months now on multiple projects. I'm toronto based working on Blockchain stuff (using Ethereum). This is not the right place for this, but I would love to buy you a coffee sometime.

Apologies for the github issue, but I figure this is the best way to get a hold of you =D.

My email:
nick.dodson@consensys.net.

**Comment by mattdesl** [comment]
Thanks and happy new year! :smile: I'm always downtown for coffee if you want to grab one. I'll send you an email.
