### ISSUE TITLE
Error starting budo

### ISSUE THREAD

**Issue by sahinyanlik** [mattdesl/budo#196]
Hello after I clone budo and npm install & npm start I got this error.

I am using windows 10 

Failed at the budo@9.4.1 start script './bin/cmd.js example/app.js:bundle.js --live -v --dir example -- -t [ babelify --presets [ es2015 ] ]'.

node version : v6.9.2

**Comment by mattdesl** [comment]
Thanks for testing. No other errors? Any reason why you are cloning and not installing from npm?

I'll give things a try on a windows machine next chance I get.

**Comment by sahinyanlik** [comment]
I just wanted to try with cloning, but npm install budo -g also doesn't work. 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\budo\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

After this when I try to start budo index.js

I get

Error: Cannot find module 'fsevents' from '\budo\node_modules\chokidar\lib'
 
Thanks

**Comment by mattdesl** [comment]
Chokidar (the file watching library) uses fsevents only on Mac OS. It should still work even without fsevents since it's just an optional dependency. 

Thanks again for testing - I'll see what I come up with in my Windows tests.

**Comment by mattdesl** [comment]
I'm testing on Windows 10 Home 64-bit with Node 6.9.4 and npm 3.5.2 and things seem good in both Git Bash and the standard cmd.exe.

However — when you git clone and `npm run start` from budo it fails because of the way the npm script is using `./` to run a shell script. I will look into making these scripts more cross-platform for those who wish to clone and run budo locally.

**Comment by mattdesl** [comment]
I've just pushed some changes to GitHub master branch which will fix that on windows when you clone and run `npm start` locally.

**Comment by mattdesl** [comment]
This should be fixed in `budo@10`. If there's any remaining issues with it, let me know and I can re-open this ticket. :smile: Cheers.
