### ISSUE TITLE
use watchify programmatically 

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#20]
pros:

- handle pending bundles easily #19 
- programmatic API can accept objects for transforms/plugins/etc
- no need to chokidar the bundle.js file 
- might simplify some code and avoid potential cross-platform woes with spawning child processes
- pretty-printing timing 
- no need for temp dir

cons:

- introduces some peer dependency woes
- for e.g. maybe pending feature should be progressively enhanced so this doesn't outright break on watchify 2.x

--

i think this is the way to go. roadmap:

- [x] watchify [resolve algorithm](https://www.npmjs.com/package/resolve-npm-which/) (Beefy's is currently not working for me)
- [x] handle pending so you are never served a stale/empty bundle
- [x] remove the debounce by default (seems unnecessary in my tests) but allow user to set `--delay`
- [x] change watcher to only look for HTML/CSS (no need for additional watchers) - breaking change
- [x] add on('update') to receive bundle events for LiveReactLoad and such
- [x] pretty-print time updates instead of using watchify's
- [x] if no `--outfile` is specified, just pipe the contents directly to the request
- [x] docs: encourage use without `--outfile` since there is no longer any temp file shenanigans
- [x] remove temp dir stuff
- [ ] explore outpipe and determine whether it's the best way forward for exorcist / uglify / etc
- [x] update demos / examples / budo-chrome / tests

**Comment by mattdesl** [comment]
i think this is the way to go. roadmap:

- [x] watchify [resolve algorithm](https://www.npmjs.com/package/resolve-npm-which/) (Beefy's is currently not working for me)
- [x] handle pending so you are never served a stale/empty bundle
- [x] remove the debounce by default (seems unnecessary in my tests) but allow user to set `--delay`
- [x] change watcher to only look for HTML/CSS (no need for additional watchers) - breaking change
- [x] add on('update') to receive bundle events for LiveReactLoad and such
- [ ] if no `--outfile` is specified, just pipe the contents directly to the request
- [ ] docs: encourage use without `--outfile` since there is no longer any temp file shenanigans
- [ ] remove temp dir stuff
- [ ] explore outpipe and determine whether it's the best way forward for exorcist / uglify / etc
- [ ] update demos / examples / budo-chrome

**Comment by mattdesl** [comment]
:thought_balloon: contemplating removing `--outfile` altogether and just sticking with a "virtual" bundle.js (pipe watchify output directly to server response). This is fast and keeps the code and API clean.

**Comment by silviopaganini** [comment]
suggestion: 
--silent (dont open the browser after server stats)

default opens browser with the localhost... 

could do it here if you're willing to implement it =)

**Comment by mattdesl** [comment]
Hmm... By default there is no command that opens the browser in budo. But I did add it to the gulp example.

**Comment by silviopaganini** [comment]
maybe I got too used to the quick prototyping and it's missing it if I run
just a npm start... could be an inverted flag then --open or something like
it

**Comment by mattdesl** [comment]
Yeah, I've been thinking about different ways to handle browser opening without adding more bulk/scope to budo. Definitely on my radar. :+1:
