### ISSUE TITLE
How to use budo with exorcist?

### ISSUE THREAD

**Issue by dmvaldman** [mattdesl/budo#200]
I need to generate a `.map` file with my bundle. It seems exorcist needs a file to work on, but `budo` serves these from memory. I'm not sure how to make the two play nicely. Any help would be appreciated.

**Comment by mattdesl** [comment]
You could try `mapstraction` instead, which doesn't rely on piping:
https://github.com/jiborobot/mapstraction

**Comment by dmvaldman** [comment]
That worked! Thank you!
