### ISSUE TITLE
Support multiple file bundles

### ISSUE THREAD

**Issue by mikeal** [mattdesl/budo#202]
It's pretty common to need a Service Worker or Web Worker in another file.

What I want is something like `budo index.js:bundle.js worker.js:sw.js` that would compile multiple end points.

**Comment by mattdesl** [comment]
Sounds good with me. 👍 Just wonder how to handle the current `--serve` API.

**Comment by mattdesl** [comment]
Closing since this is a duplicate of #139. Still not sure how to fit this into the architecture of budo (and dealing with multiple watchify instances).
