### ISSUE TITLE
Upgrade browserify

### ISSUE THREAD

**Issue by wwwtyro** [mattdesl/budo#203]
Would love to pull this in: https://github.com/substack/node-browserify/issues/1667

(sorry, wrong link previously)

**Comment by mattdesl** [comment]
Ok, I think I'll treat it as a major release of budo since browserify@14 is dropping support for old IE in the Buffer module (a breaking change). I plan on making a major bump of budo anyways for the LiveReload integration, which is pretty much complete except for some documentation.

For now you can take advantage of the latest browserify (as well as new LiveReload backend) via:

```sh
npm i mattdesl/budo#feature/livereload-rework --save-dev
```

**Comment by timwis** [comment]
Hm, that command _does_ seem to install browserify `14.1`, but I'm still getting `Unexpected token while parsing file` on the line that has `async` on it. Is there some other parser that budo uses?

**Comment by mattdesl** [comment]
It seems to work fine for me. Maybe check the following:

- Make sure you are running the right version of budo (use `budo --version` to see). Depending on whether you're using `budo index.js` from shell or `package.json` script you might get a global vs local install.
- Try uninstalling budo globally/locally and re-installing.
- Try deleting node_modules and reinstalling.
- Try the command without any transforms. The syntax error might be occurring on a transform like `brfs`.

Here's the code I'm testing:

```js
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

async function add1(x) {
  var a = resolveAfter2Seconds(20);
  var b = resolveAfter2Seconds(30);
  return x + await a + await b;
}

add1(10).then(v => {
  console.log(v);  // prints 60 after 2 seconds.
});
```

And the command I'm using:

```sh
budo index.js -o
```

**Comment by timwis** [comment]
Thanks - I disabled sheetify and it compiled, so I'll investigate sheetify

**Comment by mattdesl** [comment]
Going to close this for now since it no longer seems related to budo. Feel free to open a new issue if there's anything else. :smile:

**Comment by timwis** [comment]
Just to clarify, it looks like budo now uses browserify `14.1` per [package.json](https://github.com/mattdesl/budo/blob/master/package.json). Thanks!
