### ISSUE TITLE
ParseError: Unexpected token for <!doctype html>

### ISSUE THREAD

**Issue by Boscop** [mattdesl/budo#204]
> budo index.html --dir src --live
```html
ParseError: Unexpected token
line 1
my-app\index.html
<!doctype html>
^
```

**Comment by mattdesl** [comment]
Budo takes JavaScript files as the entry arguments and will run them through browserify. So, instead, the command should probably be:

```sh
budo src/index.js --live
```

Assuming your folder structure looks something like this:

```sh
index.html
src/
  index.js
package.json
```

**Comment by mattdesl** [comment]
Going to close since this seems like a user error. Let me know if there's anything else I can help with. :smile:
