### ISSUE TITLE
Playground mode

### ISSUE THREAD

**Issue by dfcreative** [mattdesl/budo#206]
A question/idea.

Oftentimes I find myself creating a `test.js`, installing some packages, running `budo test.js` and playing around, then deleting it. Same time for node it is enough to just run `node` and do js directly in terminal.
Wouldn't it be great for budo to have same option? Just run `budo`, play around in browser's console with exposed `require` function and that's it. Or that better fits for separate package? Maybe there are already some.

**Comment by mattdesl** [comment]
I think you might be interested in [devtool](http://github.com/jam3/devtool) which pretty much does this. It hasn't been super well maintained but it should still work for a simple playground. :smile:

**Comment by gentlefox** [comment]
This is all in-built into Chrome.
Further reading:
- [https://nodejs.org/en/docs/inspector/](https://nodejs.org/en/docs/inspector/)
- [Debugging Node.js with Chrome DevTools - Paul Irish](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27)

**Comment by mattdesl** [comment]
I don't think this really fits within budo scope, and I'm not sure how it would be possible, so I will close. Feel free to comment if there are more ideas here or like this.
