### ISSUE TITLE
Specifying your file name after the `--live` flag seems to prevent browserify from running

### ISSUE THREAD

**Issue by chinedufn** [mattdesl/budo#214]
So I started reading through the code to see what might be going on here, but figured I'd step back and open an issue in case you already had an idea.

Here's a screenshot showing my attempts to set `--live` followed by my filename:

![image](https://user-images.githubusercontent.com/2099811/28976022-3e0fc0e0-7977-11e7-913c-11073274af88.png)

So it seems like specifying the filename after `--live` prevents the `tutorial.js` (filename) argument from being parsed. If I'm reading the docs correctly it looks like `--live` doesn't accept any arguments so this seems like undesired behavior.

---

I actually ran into this months ago but never thought to change the order of my arguments :( . Came back today and accidentally changed my order and was like woah why does this work now?

I'm happy to dig into what's going on if you don't already know what might be causing this!

**Comment by mattdesl** [comment]
Yeah, this is unfortunate and not something I had considered. But `--live` at one point was a boolean, and more recently it accepts a string like `--live=*.{html,css}` to filter some file types (mainly added to make HMR easier to work with). There doesn't seem to be an easy way to detect whether `--live foo/bar.js` is desired as a bundler path, or as a filename filter. :(

Something that might help is: if `--live foo` is specified but no entry file exists, budo could print a warning about this edge case and suggest to re-order parameters. This will add additional spam to users who are legitimately trying to run budo without an entry file and with a `--live` filter, but that is probably a very small use case.

**Comment by chinedufn** [comment]
Ah thank you very much for breaking that down. Tricky tricky indeed.

# Idea Part 1:

Maybe the easier thing we can do here is update the usage docs to make it slightly more clear that `--live` takes options?

An idea:

```
# before
--live, -l       enable default LiveReload integration.
```

```
# after
--live, -l       enable default LiveReload integration on file globs. Defaults to '**/*'
```

# Idea part 2

When you run `budo` you already get a log that live reload is running:

![image](https://user-images.githubusercontent.com/2099811/28992800-318a1ac2-79e1-11e7-9ff6-c4c278fc355d.png)

> LiveReload running on 35730

Maybe we can change this to say

> LiveReload running on 35730 for files matching 'tutorial.js'

---

And haha I definitely realize that I'm maybe 1 of some small number people who have ever run into this.. but would still love to cover up my tracks here!

**Comment by mattdesl** [comment]
In 11.1.3 there is now a warning when you use the wrong order:

Also any time you specify a `--live` file name filter glob, it will print the glob below the live reload connection event.

Thanks for your feedback and sorry it took so long — little things like this make the tool much easier for newcomers. :smile:

<img width="540" alt="screen shot 2018-02-13 at 10 54 12 pm" src="https://user-images.githubusercontent.com/1383811/36187124-11a22782-1111-11e8-890d-bf2b5b19680e.png">
