### ISSUE TITLE
Save bundle to file for devtools life reload

### ISSUE THREAD

**Issue by jbraekr** [mattdesl/budo#217]
Chrome dev tools have their own editor with life reload. That works also with external files, if they are associated with a file on the file system. So saving a file with an ide triggers chromes inbuild life reload. If budo would save its bundle, it could be associated and chrome could use its own life-reload. 

Chrome life-reloads functions, keeping all data and stack intact. Which  is sometimes usefull. Break at a regex and fiddle with  it with the current data.

**Comment by mattdesl** [comment]
That's a pretty cool idea, I will test it out.

**Comment by mattdesl** [comment]
I tested this out and it's OK, but has a few major issues:

- On syntax issues and other errors (even Canvas drawing errors, like negative radius), sometimes it can't resolve itself, so you have to hard reload the page.
- If the bundle is too large, the debugger freezes (happens often in ThreeJS and React applications)
- You have to keep DevTools open during development
- It's a bit slow to resolve changes

You can achieve it with a very minimal node.js script on top of budo:

https://gist.github.com/mattdesl/c11a4cebd7fa160cbb610251678d0b9f

**Comment by mattdesl** [comment]
Going to close since I think this issue is mostly resolved.
