### ISSUE TITLE
 Server running at http://null:9966/ (connect)

### ISSUE THREAD

**Issue by dy** [mattdesl/budo#226]
When running offline/with no network devices, that IP address is in the CLI.
Should that be better ` Server running at http://127.0.0.1:9966/ (connect)`?

**Comment by mattdesl** [comment]
That's odd, I've run budo a lot offline in the past without issue. Perhaps it's something new in node/http.

In any case, I just pushed a patch for this in budo@11.2.1, please let me know if that fixes it for you.

**Comment by mattdesl** [comment]
Also, thanks for the report. 👍

**Comment by dy** [comment]
Yep, fixed, thanks!
