### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by mathisonian** [mattdesl/budo#229]
I love budo and use it for a lot of rapid prototyping stuff. However, I often want to host what I've made on Github Pages and end up trying to remember how to set up scripts to run browserify on the project and generate a boilerplate HTML, etc. I'm curious if there's any existing workflow around this that I don't know about, or if other people have developed a de facto standard way of doing it. If not would you be open to a PR for adding something in this direction?

**Comment by mathisonian** [comment]
I just found https://github.com/mattdesl/budo/issues/60, so I guess this should be closed in favor of that.

**Comment by mattdesl** [comment]
I actually want to revisit this if possible, something like `budo index.js --build --did public`
