### ISSUE TITLE
--live doesn't work with docker

### ISSUE THREAD

**Issue by oren** [mattdesl/budo#27]
fantastic library!

I am trying to make it work inside a docker container and it detects the file change but my browser does not refreshing itself. I assume it's something to do with tiny-lr and maybe some unix sockets issue between the container and my laptop. i'll investigate as soon as possible. here is the repo to reproduce my issue
https://github.com/oren/budo-template

(i might need to pass `-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix` to my run command)

**Comment by oren** [comment]
I just tried the following but it didn't help:
```` 
docker build -t budotemplate_app .
xhost && docker run -it -p 3000:3000 -p 35729:35729 -v $(pwd):/src -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --privileged budotemplate_app  npm run watch
````

**Comment by mattdesl** [comment]
budo@2 used some temp dir and file watch shenanigans for watching.  This has been cleaned up in budo@3 and now doesn't read/write to any files. 

Can you try with the latest versions of budo and watchify and let me know? Thanks!

**Comment by mattdesl** [comment]
PS Budo@3 no longer uses -o flag, so it would look like this:

`budo index.js:bundle.js --verbose --live | garnish`

**Comment by oren** [comment]
I updated to version 3 and modified the watch script as your example. still no change in the browser.

**Comment by mattdesl** [comment]
Thanks.

I'm not familiar with docker; I tried installing [docker-compose](https://github.com/docker/compose/releases) and running your commands but got the following error:

```
docker-compose build
Building app...
Couldn't connect to Docker daemon at http+unix://var/run/docker.sock - is it running?
```

I'm on OSX if that matters. If I can get the example running I will poke around a bit, too.

**Comment by oren** [comment]
I am on ubuntu. try running this: `eval "$(boot2docker shellinit)"`
also, ask on #docker i bet it will take them 20 seconds to help you out!

**Comment by oren** [comment]
yup,  `$(bootdocker shellinit)` will set `DOCKER_HOST`, `DOCKER_TLSVERIFY`, and `DOCKER_CERTS_PATH`

**Comment by mattdesl** [comment]
Ok, I got a bit further installing docker and was able to run `docker-compose build`.

Trying the second command gives me this:

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.18.5-tinycore64
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install"
npm ERR! node v1.6.4
npm ERR! npm  v2.7.5
npm ERR! path /src/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/src/package.json'
```

**Comment by oren** [comment]
I assume that you are trying to run `docker-compose run app npm install`.
It looks like mounting the current folder to /src on the image didn't work (https://github.com/oren/budo-template/blob/master/docker-compose.yml).
on mac you must clone this repo somewhere on your home. make sure that's the case.

to verify try run `ls` inside the container using this command: `docker-compose run app ls`
if you don't see the content of the repo it means that the mounting didn't work.

**Comment by oren** [comment]
If that command works try the last one: `docker-compose run --service-ports app npm run watch`
`docker-compose run` let us run  a one-off command on a service.
`docker-compose run --help` will show more options.

**Comment by mattdesl** [comment]
Ok, managed to get budo running after moving to home folder.

If I understand docker correctly, this is running some sort of virtual machine emulating a linux shell? Changing the local `app.js` source has no effect because it isn't being watched. How are you editing the `app.js` file on the virtual machine? 

Have you tested [watchify](https://github.com/substack/watchify) alone (without budo) to see if it emits change events? 

```json
"scripts": {
    "watch2": "watchify app.js --verbose --outfile bundle.js"
}
```

**Comment by oren** [comment]
docker is not a vm. it's a process that is 'special'. it's a process that give us a nice isolation (file system, mount, networking) and this process is sharing the kernel with the host (our laptops, in our case). it's an old feature of linux (chroot) that was recently wrapped with an easy to use API.

You can edit all your files (app.js in our case) as usual on your laptop. use vim/sublime/whatever. thanks to the volumes key (https://github.com/oren/budo-template/blob/master/docker-compose.yml) we can mount the project's folder into the container so our project's folder is available to the container.

I tried your watch2 script and it detect the file change. both watchify alone and budo are detecting the file change. i know it since i see it in the log. what doesn't happened is my browser does not refresh. i need to figure out a way to tell the container that my chrome is running on my laptop and not inside the container.

**Comment by mattdesl** [comment]
Ok, cool. Not sure why it would act any differently. If you aren't seeing LiveReload requests in the network tab in Chrome (on filesave) then the tiny-lr script isn't getting sent to the currently running LiveReload server. Also you may want to test CSS/HTML reloading since it has a slightly different mechanism than reloading the JS bundle.

**Comment by oren** [comment]
i'll dive into tiny-lr and update my findings here later on. thank you.

**Comment by mattdesl** [comment]
I'm going to close this since it seems to be out of scope for this tool. We can always open another issue at a later point if something feels missing in budo. :smile:
