### ISSUE TITLE
Sourcemap header?

### ISSUE THREAD

**Issue by tmcw** [mattdesl/budo#29]
Should budo expose a header like this to indicate where a source map exists? Running 3.0.0 doesn't seem to have Google Chrome loading the sourcemap anymore.

```
X-SourceMap: /path/to/file.js.map
```

**Comment by mattdesl** [comment]
Browserify uses inline source maps so there is no `.map` file. The typical solution is [exorcist](https://www.npmjs.com/package/exorcist) for external source maps.

I just tested with Chrome 42 and budo@3.0.4 and source maps seem to be working here. Any more details or something I can reproduce?

**Comment by tmcw** [comment]
:+1: budo 4.0.0 seems to work again, something was off with my previous configuration.
