### ISSUE TITLE
Subarg syntax

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#30]
Should support subarg syntax in CLI e.g. for transforms

**Comment by mattdesl** [comment]
For now, you can use the `--` to add "unparsed" arguments to the list:

```sh
budo index.js --live -v -- -t [ babelify --some-options=foobar ]
```

Revisiting this later as it is pretty complicated. Could do some [regex replace](https://github.com/mattdesl/subarg-replace) but it gets a little nasty. The "proper" way to fix is just enforcing `--` for all browserify options, but the UX is not as pleasant.

**Comment by peteschaffner** [comment]
On a semi-related note, is there any way to pass args to transforms via the API?

**Comment by peteschaffner** [comment]
I only ask because I have been beating my head against the wall trying to use a global transform :)

**Comment by mattdesl** [comment]
@peteschaffner Most transforms provide a way to configure options, so you could do something like this:


```
budo(entry, {
  transform: babelify.configure({
    blacklist: ["regenerator"]
  })
})
```

**Comment by peteschaffner** [comment]
Sorry, I misspoke earlier. I meant to ask if there was a way to pass transform options to `browserify` (not options to transforms). In other words, I need to pass `{ global: true }` to `browserify` for a certain transform.

**Comment by mattdesl** [comment]
As I see; that's tricky.

Maybe this?

```
budo(entry, { 'global-transform': 'foobar' })
```

I'll open another issue to track this

**Comment by mattdesl** [comment]
5.0.0 fixes this by not allowing any browserify options before the `--` full stop
