### ISSUE TITLE
Globally Installed Watchify Not Supported

### ISSUE THREAD

**Issue by MikkoH** [mattdesl/budo#32]
With a globally installed version of Watchify@3.1.2. I get the following error:
```
Error:
  could not find watchify/bin/args.js - unsupported watchify version
```

Watchify is not installed a local dependency.

**Comment by mattdesl** [comment]
This will get fixed with #33 but might be worth figuring out why it's broken. Can you try:

`npm install -g npm-which`

Then:

`npm-which watchify`

And let me know the path

**Comment by MikkoH** [comment]
```
/usr/local/bin/watchify
```

**Comment by mattdesl** [comment]
closing as 4.0 no longer looks for global watchify
