### ISSUE TITLE
Multiple ports for live reload

### ISSUE THREAD

**Issue by superguigui** [mattdesl/budo#34]
Hi !

What do you think about using `getport` for `--live` the same way you do it for the [server port](https://github.com/mattdesl/budo/blob/master/index.js#L54). It would be useful when having multiple budo instances running at the same time to have an auto live port pick from budo, for now it's either 35729 or `--live-port` but it won't work well if we select the same port multiple times  (or if we don't select `--live-port` at all multiple times).

I'm currently working on a PR to add this feature (see [this commit](https://github.com/superguigui/budo/commit/c437bfddb781816372372afd621214ad18daa87f)) but I have a hard time finding where the live reload `<script>` tag is inserted in the html, could you give me some pointers?

Thanks for your work on this cool lib, I'm using it a lot lately :)

Cheers

**Comment by mattdesl** [comment]
:+1: 

The port/host options for the `<script>` tag are set like this: 
https://github.com/mattdesl/budo/blob/master/lib/budo.js#L116

You could add a callback to `createTinylr` which is called when the server is connected, and then update the `server._live` with the new port.

Also; right now the API does not do auto port-finding. For consistency I think the API should either do auto portfinding everywhere that the CLI does, or maybe no portfinding at all. Hmm

**Comment by superguigui** [comment]
As a matter of fact I also started implementing the portfinding on the API :D [commit](https://github.com/superguigui/budo/blob/live-reload-multiport/lib/index.js)

I'm definitely voting for keeping portfinding but it might need a bit of refactoring, maybe a findPort method that we will use for CLI, API and live. Why would you want to remove portfinding at all? It's a sweet feature in my opinion :)

Thanks for your answer, I'll have a look at all this !

**Comment by mattdesl** [comment]
this is supported in 5.0.0

see the pre release here:
https://github.com/mattdesl/budo/tree/next
