### ISSUE TITLE
how to bundle js with budo?

### ISSUE THREAD

**Issue by minjiex** [mattdesl/budo#35]
I use '  node_modules/.bin/budo  main.js  -- -o bundle7.js   '  , but cannot output anything. Can anyone help me?

**Comment by mattdesl** [comment]
Budo doesn't do any file reading or writing. To write to a file you can just use the Browserify directly. Also see:
https://github.com/mattdesl/budo/issues/31

**Comment by minjiex** [comment]
@mattdesl  I see.. Thanks a lot!!
