### ISSUE TITLE
bundle.js is not being generated

### ISSUE THREAD

**Issue by oren** [mattdesl/budo#36]
`budo app.js:bundle.js --port 3000 --verbose --live`

am I doing something wrong?

**Comment by mattdesl** [comment]
Hey oren, 

budo doesn't actually write any bundle files to disk. It just serves the browserified contents when they are requested (ie. when you open localhost:3000 in a browser). 

To create a production bundle you should still use browserify. :) 

I should add a note in the docs to make this clearer. 

Hope that solves your issue?

**Comment by oren** [comment]
i am almost there (:

here is my watchify. can you help me with the budo command?
my server is running on port 3000.

```  
 "watch-js": "watchify ./js/app.js -t brfs -t envify -d -o ./bundle.js",
 "refresh": "budo ./js/app.js:bundle.js --port 3000 --verbose --live"
```

**Comment by mattdesl** [comment]
The budo CLI exists to *replace* watchify and your local server (e.g. it replaces `http.createServer` or `http-server`). Your local development command would be:

```
budo ./js/app.js:bundle.js --port 3000 --verbose --live -t brfs -t envify
```

For example, here is what it might look like in practice. budo is used for quick local development, and browserify is used to create a production bundle.

https://github.com/mattdesl/three-glslify-example/blob/eb149953f1834b93fb72e4edfebe100ed9faa6a1/package.json#L28-L29

**Comment by oren** [comment]
in my project I have 2 folders: client and server. 
the server is running express on port 3000 and it provide a few endpoints to and Angular app.
The angular app is inside the client folder and served by the server using this line: 
`app.use(express.static(path.join(__dirname, '../client')));`

How do I use budo in this case?

**Comment by mattdesl** [comment]
So far this project only targets static sites. It creates its own server and handles its own routing. So you would not be able to use it with express.

At some point some of the code might be refactored into smaller modules e.g. a `watchify-middleware` or something, to better facilitate use cases like this.  

If anyone has ideas for this I'm all ears. 😁

**Comment by oren** [comment]
got it! maybe it's a good time for me to refactor my codebase into 2 separate projects. one using express and the other is served by nginx.

**Comment by mattdesl** [comment]
closing since this seems resolved

**Comment by archanag172** [comment]
how to fix this issue.

Failed to load resource: the server responded with a status of 404 (Not Found)
favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by mattdesl** [comment]
Hi @archanag172, usually that error appears if you have a `<script src="bundle.js">` tag in your index HTML, but nothing that serves a file called `bundle.js`. To resolve it, you could either:

- Remove the `<script>` tag from the HTML or replace it with a correct one
- Or keep it pointing to `bundle.js`, but use the `--serve` or "remap" feature when starting budo, like this:  
`budo src/index.js:bundle.js --live`

Feel free to open a new issue if you are still having trouble.
