### ISSUE TITLE
b.transform opts

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#37]
When creating a custom bundler, you can pass `opts` to `b.transform()` like `global: true`. 

This might be possible with `'global-transform'` option but it is not well documented via browserify API.

Another option might be to allow a custom `bundler` object passed via budo API, in which case all other options are ignored. 
hmm

see discssion #30

**Comment by peteschaffner** [comment]
Unfortunately `'global-transform'` doesn't work. I've been reading through browserify and budo source, but I'm having a hell of a time figuring out what happens with the `transform` value once passed to watchify.

Can you elaborate a little more on the custom `bundler` idea?

Thanks for your willingness to look into this, btw! :)

**Comment by mattdesl** [comment]
Here is the relevant part of browserify's arg parsing and why it would probably work fine if you run budo from the CLI:
https://github.com/substack/node-browserify/blob/b065829be44a214d2bb9817933aee988ff6d1599/bin/args.js#L180-L184

Unfortunately it looks like Browserify's API doesn't expose a `globalTransform` option in the constructor like it does the `transform` option:

https://github.com/substack/node-browserify/blob/b065829be44a214d2bb9817933aee988ff6d1599/index.js#L84-L87

So it seems like the only way to achieve it would be to set up the bundler outside of budo:

```js
var b = browserify({ ... options ... })
b.tranfsorm(something, { global: true })

budo(b)
```

I'm not a huge fan of this since it adds a lot of complexity to budo. :disappointed: 

Alternatively, we could add an issue to node-browserify and try to get a `globalTransform` option in the constructor. 

I will brew on this a bit more ...

**Comment by peteschaffner** [comment]
Thanks a lot for linking to the relevant parts!

Yeah, requiring a custom bundler be passed to budo definitely feels like it is going against the design of your API (not to mention the new hard dependency on browserify in any project that uses budo would be a drag).

What if we took a middle road and allowed passing the current `entry[, opts]` arguments **or** a custom bundler object to budo? Let me know if this is feasible and if so, I can take a crack at it ... although I might need a little direction from you ;)

Either way, I will open an issue with browserify for a `globalTransform` option as you suggested.

**Comment by peteschaffner** [comment]
Ok, I opened an issue upstream in substack/node-browserify#1267.

FYI, just for some context, I am making a [Framer.js CLI](https://github.com/peteschaffner/framer-cli), and would like to globally resolve relative asset paths (i.e. `image: 'images/myImage.png`) for all third-party modules. My current solution has been to create a separate (and dirty) transform and explicitly declare it in said modules, but I would like this to be the default (and thus a global transform).

**Comment by mattdesl** [comment]
Here is a fix for the time being, in the `feature/global-transform` branch:
https://github.com/mattdesl/budo/tree/feature/global-transform

Will sit on it for a bit and see how your issue is received by the browserify folks. If it's fixed upstream then budo won't need any changes.

**Comment by peteschaffner** [comment]
Awesome! Sounds like a good plan.

**Comment by mattdesl** [comment]
@peteschaffner did substack's suggestion fix your use case? Do you feel strongly one way or another with regard to changing things in budo?

Cheers :beers:

**Comment by peteschaffner** [comment]
Hey @mattdesl, sorry for the delay. Yep his suggestion worked for me so I'm all for leaving budo's API alone :)

Thanks again for investigating this with me.

**Comment by mattdesl** [comment]
cool, will close this then
