### ISSUE TITLE
Use ip over localhost

### ISSUE THREAD

**Issue by MikkoH** [mattdesl/budo#39]
Currently if you're for instance running budo on desktop and trying to debug mobile live reload fails because the livereload script tries to load from localhost.

Might be good to use: 
https://www.npmjs.com/package/internal-ip

And replace locahost with the internal ip of the server.

**Comment by mattdesl** [comment]
You can do this:

```sh
# install tools
npm install internal-ip budo opnr garnish -g

# run internally and open in browser
budo test.js --host=`internal-ip` | opnr | garnish
```

The downside is that you can't just open `localhost:9966` anymore, instead you need to open the internal IP.

**Comment by mattdesl** [comment]
added to docs
https://github.com/mattdesl/budo/blob/master/docs/basics.md#internal-ip

**Comment by mattdesl** [comment]
actually it seems like browser-sync is able to serve `localhost` as well as internal-ip 
gotta look into how they do that

**Comment by mattdesl** [comment]
K, so it looks like `browser-sync` uses some sort of proxy to support `localhost` as well as the internal IP. Ideally I'd like to keep budo simple/focused and just serve the specified port/host, without any magic.

I'll leave this open for discussion/etc. If there's a simple solution, I could be open to adding it.

**Comment by mattdesl** [comment]
in `next` branch
