### ISSUE TITLE
Feature proposal; proxying

### ISSUE THREAD

**Issue by asbjornenge** [mattdesl/budo#45]
Hi @mattdesl, and thanks a bunch for budo! I really like it :grin: 

I would also like to use it for work, but have a challenge. Our "API" at work is this complicated distributed mess. It's not really feasible to run all the required pieces on a laptop. So I need to "connect" to an environment to get data. My proposal is; **configurable proxy paths for budo**.

There are several ways to go about it, but the basics would be to configure a local path to a proxy server;

```
budo app.js --proxy /api:http://localhost:8080/api
```

Translates to; any calls to **http://budo-dev-server/api** should be proxied to **http://localhost:8080/api**

This way the proxied-to server can be any arbitrary server, and we avoid baking any knowledge about how the proxy works into budo. I have lots of requirements for my proxy, it needs to perform auth, logging etc. But all this logic can go into my localhost:8080 server allowing me to connect to my complex backend from budo :smile:

**Comment by mattdesl** [comment]
Where does `http://budo-dev-server/api` come from? Is this hard-coded or something the user would define?  

What API/modules are typically used for proxying? Any examples out there in the wild? 

I'm also interested in proxying the internal IP like BrowserSync does, so it might be feasible under the same feature. I haven't done anything like that though (still pretty green on server-side dev).

Cheers :beer:

**Comment by asbjornenge** [comment]
By `http://budo-dev-server` is mean the `http://localhost:9966` that budo spins up... 

If you try the `/api` path now, we get `File not found :-(`, which is fine. But if we add a `--proxy /api:http://yolo.com/api`, any calls to `http://localhost:9966/api` should return the result of `http://yolo.com/api` - did that make sense? :stuck_out_tongue_winking_eye: 

How to go about doing the actual proxying depend a bit on how you are currently creating the http server. There are modules like [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) and lots of middleware if you are using express or similar. But it can be as simple as:

```
var proxy = function(req, res) {
    var proxyReq = {
        method : req.method,
        url : pickProxyPath(req) // <- figure out the new url
    }
    var body = ""
    req.setEncoding('utf8');
    req.on('data', function(chunk) { body += chunk })
    req.on('end', function() {
        proxyReq.body = body
        require('request')(proxyReq, function(err, proxyResponse, body) {
            res.writeHead(proxyResponse.statusCode, proxyResponse.headers
            res.write(body)
            res.end()
        })
    }.bind(this))
}
require('http').createServer(function(req, res) {
    if (isProxy(req)) return proxy(req, res) // <- if we should proxy, proxy...
    // if not, do current browserify magic
})
```
Ok, that probably won't work if you copy-paste it, but hopefully you get the gist :smile: 

I'm not quite sure what you mean by *proxying the internal IP* ... care to elaborate? What do you want to do?

**Comment by mattdesl** [comment]
I probably won't add this feature any time soon since it seems to introduce a fair bit of complexity into the code. If there is high demand for it I will reconsider and reopen. Cheers. :smile:

**Comment by brokenalarms** [comment]
ah, just looked for exactly the same reason since we have the same setup at work. we have a gulp frontend task that runs the frontend on port x, then proxies requests through to the backend api server running on y. Was wondering why my requests weren't being received by the the api server at all until I saw this, of course. Back to gulp for now then :/ Great dev server for home though :)

**Comment by tlenczyk** [comment]
The same here. I have java server exposing REST API lets say on http://localhost:8080/api
I would like to to proxy all API request to my backend API. For example here (https://github.com/indexzero/http-server) it is implemented as additional -p parameter

**Comment by edap** [comment]
damn, I was looking exactly for this feature. I'm developing an app locally and I run the backend on localhost:3001 and the frontend react app with budo on localhost:3000, i was looking for a way to get the data from my API.

**Comment by knoan** [comment]
+1
