### ISSUE TITLE
inject LiveReload script into existing index.html?

### ISSUE THREAD

**Issue by jessaustin** [mattdesl/budo#46]
A LiveReload script is included in the bare-bones `index.html` that is generated when no `index.html` exists in the directory. When there is an `index.html` file in the directory, that gets served instead. It would be convenient if the LiveReload script were injected into this existing `index.html`.

**Comment by mattdesl** [comment]
Hmm this should have been fixed a while back - #5.

Can you make sure you're on the latest version? `budo --help` should report version 4.0.0 or higher. If not, update and give it another shot:

```sh
# if you are using it globally
npm install budo -g

# if you are using it locally with "npm-scripts"
npm install budo --save-dev
```

:smile:

**Comment by jessaustin** [comment]
I'm at `4.1.0`. I figured out what's wrong. I didn't have an explicit `<body>` tag in my `index.html`. Although browsers will infer a `<body>` tag, leaving it out is probably not "best practice". :smile: Sorry for the noise!

**Comment by mattdesl** [comment]
Ah, thanks. :smile: I opened an issue upstream:

https://github.com/mattdesl/inject-lr-script/issues/1

**Comment by mattdesl** [comment]
I'll also keep this issue open until its also resolved in budo (might just end up documenting it as a "Gotcha").

**Comment by mattdesl** [comment]
Added [a note about this](https://github.com/mattdesl/budo/blob/next/docs/command-line-usage.md#live-reload) in docs; solving it would be too much of a hassle.
