### ISSUE TITLE
how do I turn off debug lines in console?

### ISSUE THREAD

**Issue by mark-hahn** [mattdesl/budo#51]
I'm seeing a ton of lines like this in my console

```
{"time":"2015-07-31T21:36:54.978Z","hostname":"localhost","pid":24816,"level":"info","name":"budo","url":"/sample4.png","type":"static"}
```

How do I turn these off?  I saw the option `--no-debug` but I need the source-maps.  I couldn't find any mention of setting the debug level in the docs folder.

**Comment by mattdesl** [comment]
You can use the following:

```sh
budo index.js --no-stream
```

Alternatively, you can install [garnish](https://github.com/mattdesl/garnish) (or any other ndjson pretty-printer) and pipe content into it.

```sh
npm install garnish -g

# now pipe ndjson into garnish
budo index.js | garnish
```

**Comment by mark-hahn** [comment]
Thanx.

P.S. I didn't know garnish would remove lines.
