### ISSUE TITLE
Onchange commands from CLI

### ISSUE THREAD

**Issue by cvan** [mattdesl/budo#58]
Is there a way from the command line to call a command when the file watchers detect a change?

I want to be able to run linters when `budo` detects a `.js` file is changed - but I don't want to add another file watcher to the mix. For example:

```
budo -- --onchange npm run lint
```

**Comment by mattdesl** [comment]
This could be handy, and seems to be a desired feature for dev tools. Same thing here:
https://github.com/Jam3/hihat/issues/22

It would probably look like this, for parity with `'update'` event which is only triggered when the bundle is finished reloading.

```sh
budo --onupdate "npm run lint" -- [browserifyOpts]
```

What is the desired result of success/fail on lint? Just pipe the child stdout/stderr to the terminal?

**Comment by mattdesl** [comment]
Testing out the feature [here](https://github.com/mattdesl/budo/tree/feature/cli-onupdate).

You can install it like so:

```sh
npm install -g mattdesl/budo#6372153e443ed707f5556dac04d2801481a670e1
```

Then, with your favourite linter, like [standard](npmjs.com/package/standard).

```sh
budo src/index.js --onupdate "standard" | garnish
```

**Comment by cvan** [comment]
Thanks so very much for jumping on that - and so quickly!

The only issue is when I pipe `garnish`, I see a bunch of newlines that I think are getting triggered from the output from `standard`.

<img width="1129" alt="screen shot 2015-09-10 at 12 22 30 pm" src="https://cloud.githubusercontent.com/assets/203725/9801405/aeb41bee-57c7-11e5-8d2c-636a35e3e90e.png">

If I remove the `| garnish`, everything looks okay (but then the requests get gross, heh).

Any ideas how I could prevent `garnish` from trying to parse that? Shouldn't it just be looking for anything that looks like an object?

**Comment by mattdesl** [comment]
Hmm strange. Here's what my terminal looks like after using it for a bit:

<img width="682" alt="screen shot 2015-09-10 at 7 11 30 pm" src="https://cloud.githubusercontent.com/assets/1383811/9803371/c8edb560-57ef-11e5-80c1-6f602be05a78.png">

I'm using `garnish@3.2.0` and `standard@5.2.2`, both run locally within npm `"scripts"` field.

The only time GET should come up is when a server request has finished, so maybe you are seeing a different bug?

**Comment by cvan** [comment]
I upgraded `garnish` and it worked. This is fantastic. Thanks so much - this is already super useful.

**Comment by mattdesl** [comment]
You might also like this:
https://github.com/mattdesl/notify-error

Example: 

```sh
budo index.js --onupdate "standard | notify-error"
```

When a lint error occurs, you get a beep and notification like this:

<img width="353" alt="erro" src="https://cloud.githubusercontent.com/assets/1383811/9977335/0b1de3d2-5ed1-11e5-86e6-1dc2f2003657.png">

**Comment by cvan** [comment]
Love it!

**Comment by mattdesl** [comment]
merged with the `next` branch
