### ISSUE TITLE
--debug by default?

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#6]
beefy uses `-d` by default to enable source maps... not sure if this is the way to go. 

But I find myself adding it every time i'm using budo for dev

**Comment by tmcw** [comment]
:+1: same here, source maps are the norm for debugging. Thanks for budo, it's working great in my dev process.

**Comment by mattdesl** [comment]
I agree... 

There's a couple [rare cases](https://twitter.com/mattdesl/status/577579659245780992) where you might not want source maps though, so it would be nice to have a way to turn it off. I could maybe add support for `--debug=false` although it diverges very slightly from browserify.

And thanks! Let me know if there's any other issues. :ok_hand:

**Comment by mattdesl** [comment]
debug is now default in `1.3.0`

source maps can be removed with `--debug=false` or `--no-debug`
