### ISSUE TITLE
tinylr error messages

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#61]
should probably clean this up to avoid swallowing any errors:
https://github.com/mattdesl/budo/blob/0938e878d92f1d2f5e4521a9b5f4a84f61c2c2ae/lib/tinylr.js#L27

**Comment by yoshuawuyts** [comment]
Tried patching the code, but bundle comparison test failed:
```js
  serverImpl.on('error', function(err) {
    if (err.code === 'EADDRINUSE') {
      process.stderr.write('ERROR: livereload not started, port ' + opt.port + ' is in use\n')
    } else process.stderr.write(err)
    close()
  })
```

Running npm install with the `vm` package in devDependencies didn't work on `npm@2.14.2`, so I removed it... which is what I suspect caused the bundle comparison to fail.

**Comment by mattdesl** [comment]
I'll take a look this weekend 👌

**Comment by mattdesl** [comment]
fixed

@yoshuawuyts 
The `vm` module is part of Node core, no need to install it.

With `npm run test`, all are passing for me on `npm@2.11.3` and `node@0.12.7`. Some of them will fail if you're already running a server on certain ports.

**Comment by yoshuawuyts** [comment]
Yeah, but having it in [`devDependencies`](https://github.com/mattdesl/budo/blob/master/package.json#L47) caused my `npm install` to misbehave. Might want to remove it (though that tests to fail on me on `node@4`):
```txt
~/src/mattdesl/budo master
❯ npm i
npm WARN package.json Dependency 'inject-lr-script' exists in both dependencies and devDependencies, using 'inject-lr-script@^1.0.0' from dependencies
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/yw/.nvm/versions/node/v4.0.0/bin/node" "/Users/yw/.nvm/versions/node/v4.0.0/bin/npm" "i"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/vm
npm ERR! 404
npm ERR! 404 'vm' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404
npm ERR! 404  1. vm is a core module name
npm ERR! 404 It was specified as a dependency of 'budo'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yw/src/mattdesl/budo/npm-debug.log

~/src/mattdesl/budo master
❯ node -v
v4.0.0
```

**Comment by mattdesl** [comment]
Woops, it shouldn't be in there. Removed. :smile:
