### ISSUE TITLE
[question] favicon handling

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#69]
Currently `budo@next` is serving a default `favicon.ico` to avoid 404s in terminal/browser console and DevTools. It is also being muted, without any ndjson logs, to reduce clutter.

However, maybe this is a bit too magical, as it could interfere with a user's intended favicon. Should it be changed/removed?

Here is a run with two hard reloads in Chrome.

Current behaviour:
<img width="368" alt="screen shot 2015-09-24 at 10 35 58 pm" src="https://cloud.githubusercontent.com/assets/1383811/10091720/b4117bd6-630c-11e5-9f5c-89d21a451848.png">

With logging:
<img width="368" alt="screen shot 2015-09-24 at 10 36 18 pm" src="https://cloud.githubusercontent.com/assets/1383811/10091718/b40dcc48-630c-11e5-8ef9-36dc4819ef9e.png">

No special handling:
<img width="368" alt="screen shot 2015-09-24 at 10 35 19 pm" src="https://cloud.githubusercontent.com/assets/1383811/10091721/b41225e0-630c-11e5-8864-68d304a6e19a.png">

**Comment by bendrucker** [comment]
I'm +1 to the default favicon. Can't really ever think of a reason I'd want a custom one.

**Comment by mattdesl** [comment]
Cool thanks for the input :+1:

**Comment by bendrucker** [comment]
It's the least I can do!

**Comment by mattdesl** [comment]
Seems like this is OK to close now.
