### ISSUE TITLE
Pages must end in `.html` for LiveReload script to be injected

### ISSUE THREAD

**Issue by cvan** [mattdesl/budo#72]
1. create a directory called `demo` and place in it an `index.html` with a `<script src="../bundle.js">`.
2. run budo.
3. load [http://localhost:9966/demo/](http://localhost:9966/demo/) in your browser.
4. view source.
5. notice the LiveReload script wasn't injected into the HTML response.

because the router whitelists only `*.html`, the script doesn't get injected. same thing happens for files ending in `.htm` (not `.html`).

the correct but slow thing would be to check the mime-type after ecstatic reads the file. but we don't want to muck with the stream, and since it's already a dev tool intended for serving `.html` files, we ought to just tweak the route's regex.

**Comment by mattdesl** [comment]
Actually, the script injector is already doing the mime-type check:
https://github.com/mattdesl/inject-lr-script/blob/551f0858b509d4f25ff96d4f832d055d0532994d/index.js#L26-L27

The regex PR seems good though, it handles most common cases.
