### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#76]
Should probably add https support, especially as lots of cool things are being deprecated in HTTP.
https://twitter.com/msfeldstein/status/648338593489027074

**Comment by msfeldstein** [comment]
I've got a branch mostly working just finishing up livereload and figuring out some tests: https://github.com/msfeldstein/budo/tree/AddSSL ... depends on https://github.com/mattdesl/inject-lr-script/pull/2

**Comment by mattdesl** [comment]
Awesome. Feel free to PR and I can fix up the tests this week. :smile:

**Comment by mattdesl** [comment]
Hmm - I'm a bit unfamiliar with SSL. How did that cert get generated? Is it just a 'generic' cert to allow mic/etc? Is this something that should be configurable for the user, so they can provide their own certs?

**Comment by msfeldstein** [comment]
Yeah I used the instructions here to create a generic (just pressed enter for all defaults) certificate: http://greengeckodesign.com:8880/blog/2013/06/15/creating-an-ssl-certificate-for-node-dot-js/

Was thinking of adding an npm task to allow users to generate them themselves, I agree it feels a little sketchy to be shipped non-readable files, especially involving security.  For a prototyping tool like this I could go either way, but let me see what I can do about making an easy 'cert-generator' to run locally.

**Comment by msfeldstein** [comment]
Also the first time you do this chrome will show the "This certificate is not valid, danger" alert that you need to click "proceed anyway" on.  Want to give this all just a little more thought before I PR it, but there's a good chance there's no way around that part.

Though https://letsencrypt.org/ is a new effort to make cert generation easy and free so maybe there's some way to leverage that, but I haven't actually looked into how they work yet.

**Comment by yoshuawuyts** [comment]
`wzrd` uses [pem](https://github.com/andris9/pem) to generate certs; reckon that's the right way to go since it works offline

**Comment by mattdesl** [comment]
I added a "first pass" at SSL which matches the [http-server](https://www.npmjs.com/package/http-server) behaviour, we can explore using `pem` to generate certs in another version.
