### ISSUE TITLE
ENOSPC error with default file watch glob

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/budo#82]
See here:
https://github.com/mattdesl/wtch/issues/2

One solution is to prepend `__dirname` to the default globs. I don't know whether this will have any unintended side-effects.

**Comment by tunnckoCore** [comment]
I think `process.cwd` or something like that would be enough and won't have side-effects.

**Comment by mattdesl** [comment]
I haven't seen this in a couple years.... 😂 I'm going to close it. Let me know if it's still an issue.

**Comment by tunnckoCore** [comment]
@mattdesl :+1: me too :joy:
