### ISSUE TITLE
Send multiple transforms to browserify

### ISSUE THREAD

**Issue by silviopaganini** [mattdesl/budo#97]
for example babelify and glslfy, didnt manage to get both working together, maybe there's a way that I haven't found out yet

**Comment by mattdesl** [comment]
You can do this:

```sh
budo index.js -- -t babelify -t glslify
```

However, you can't use `import` on glslify yet:

```js
// regular ES6 imports
import assign from 'object-assign'

// use CommonJS require for glslify
var glslify = require('glslify')
```

It's a bug with `static-module`. 
https://github.com/stackgl/glslify/issues/49

**Comment by silviopaganini** [comment]
yeah, I tried that, but it keeps giving me `glslify not defined`





--
Silvio Paganini // +44 753 4915 733 // s2paganini.com
twitter @silviopaganini <http://www.twitter.com/silviopaganini>

**Comment by silviopaganini** [comment]
budo 4.1.0

**Comment by silviopaganini** [comment]
`"start": "budo --dir dist/ src/index.js:js/bundle.js -v --live --host localhost -- -t babelify -t glslify | garnish",`

that's my start command

**Comment by mattdesl** [comment]
Hmm you have `glslify` as a devDependency?

**Comment by silviopaganini** [comment]
yep `"glslify": "^2.3.1",`

tried installing as -g and didn't work too 

importing like I was doing before: 

```
const glslify = require('glslify');
console.log(glslify);
```

any ideas?

**Comment by mattdesl** [comment]
Can you git clone this repo and `npm install` then `npm start` to see if it works?

https://github.com/mattdesl/three-glslify-example/blob/master/package.json

It uses babelify + budo@5 + glslify.

**Comment by silviopaganini** [comment]
that works, let me try to update budo

**Comment by silviopaganini** [comment]
seems to work =) no idea why though !!

**Comment by mattdesl** [comment]
Strange, the old version was doing some odd stuff which has since been cleaned up. Closing.

**Comment by marklundin** [comment]
Just dropping this in here for future reference as I also ran into this.

Seems it's more an es2015 thing using template literals to define the shader string. The [stack.gl particle demo](https://github.com/stackgl/gl-particles) for example doesn't run with budo out of the box unless you have babel or similar

You can solve by replace the template literals with regular strings, using babel, or upgrading Node.
